name: PersianChat
main: PersianChat\Main
version: 1.0.0
api: [5.21.1] # نسخه API سرور PocketMine یا Piggot
description: A plugin to reverse and fix Farsi text in chat.
author: ShahabManoochehri
